@startuml diagrama

abstract Class Autopista {
    vehiculos 
    saldo

    cobrarPeaje()
    cobrarleA(unVehiculo)
}

abstract Class Vehiculo {
    tarifa
    efectivo
    saldoSube
    peajesDisponibles
    metodoDePago

    {abstract} tarifa()
    pagarPeaje()
    disminuirPeajesDisponibles(unValor)
    disminuirSaldoDeSube()
    disminuirEfectivo()
}

Class Auto extends Vehiculo {
    tarifa()
}

Class Camion extends Vehiculo {
    cantidadDeEjes

    tarifa()
}

object conPass {
    pagarSegunMetodo(unVehiculo)
}

object conSube {
    pagarSegunMetodo(unVehiculo)
}

object conEfectivo {
    pagarSegunMetodo(unVehiculo)
}

interface metodoDePago {
    pagarSegunMetodo(unVehiculo)
}

Autopista --> "*" Vehiculo : vehiculos
Vehiculo -l-> metodoDePago
conPass .u.|> metodoDePago
conSube .u.|> metodoDePago
conEfectivo .u.|> metodoDePago



@enduml