@startuml diagrama

Class Parque {
    visitantes 
    saldo 

    cobrarEntrada()
    cobrarleA(unVisitante)
}

abstract Class Visitante {
    metodoDePago

    {abstract} tarifa()
    pagarEntrada()
}

Class Niño extends Visitante {
    tarifa()
}

Class Adulto extends Visitante {
    tarifa()
}

Class ConPaseRapido {
    accesosDisponibles

    pagarSegunMetodo(unMonto)
}

Class ConTarjeta {
    saldoTarjeta

    pagarSegunMetodo(unMonto)
}

interface metodoDePago {
    pagarSegunMetodo(unMonto)
}

Parque --> "*" Visitante : visitantes
Visitante -l-> metodoDePago
ConPaseRapido .u.|> metodoDePago
ConTarjeta .u.|> metodoDePago


@enduml