@startuml diagrama

class Parque {
    visitantes
    saldo

    cobrarEntrada()
    cobrarleA(unVisitante)
}

interface visitantes {
    pagarEntrada()
    tarifa()
}

abstract class Nino {
    accesosDisponibles
    saldo
    formaDePago

    tarifa()
    {abstract} pagarEntrada()
    disminuirSaldo(unMonto)
    disminuirAccesos(unaCantidad)
}

abstract class Adulto {
    accesosDisponibles
    saldo
    formaDePago

    tarifa()
    {abstract} pagarEntrada()
    disminuirSaldo(unMonto)
    disminuirAccesos(unaCantidad)
}


interface formaDePago {
    valorAgregado(unVisitante)
}

object conEfectivo {
    valorAgregado(unVisitante)
}

object conPrepaga {
    valorAgregado(unVisitante)
}

object conPaseRapido {
    valorAgregado(unVisitante)
}


Parque --> visitantes 
Nino .u.|> visitantes
Adulto .u.|> visitantes
Nino --> formaDePago
Adulto --> formaDePago
conEfectivo .u.|> formaDePago
conPrepaga .u.|> formaDePago
conPaseRapido .u.|> formaDePago

@enduml