@startuml diagrama

abstract Class PeliculaVol2 {
    personajes 

    protagonista()
    noEsVaron()
    rompeEstereotipos()
    {abstract} condicionExtraSegunGenero()
}

Class PeliAventuraVol2 extends PeliculaVol2 {
    condicionExtraSegunGenero()
}

Class PeliTerrorVol2 extends PeliculaVol2 {
    condicionExtraSegunGenero()
}

Class PeliComediaVol2 extends PeliculaVol2 {
    condicionExtraSegunGenero()
}

interface personajes {
    sosActuado()
    esRescatado()
}

Class PersonajeActuado {
    genero
    esRescatado

    sosActuado()
    genero()
    esRescatado()
}

Class PersonajeAnimado {
    sosActuado()
    esRescatado()
}

PeliculaVol2 -l-> "*" personajes : personajes
PersonajeActuado .u.|> personajes 
PersonajeAnimado .u.|> personajes

@enduml