@startuml diagrama
Class Calendario {
    eventos 

    estaLibre(unaFecha)
}

Class EventoDiaCompleto {
    fecha 

    tieneLibre(unaFecha)
}

Class Recordatorio {
    tieneLibre(unaFecha)
}

interface eventos {
    tieneLibre(unaFecha)
}

Calendario --> eventos
EventoDiaCompleto .u.|> eventos
Recordatorio .u.|> eventos
@enduml