@startuml diagrama

abstract Class Autopista {
    vehiculos 
    saldo

    cobrarPeaje()
    cobrarleA(unVehiculo)
}

abstract Class Vehiculo {
    metodoDePago

    {abstract} tarifa()
    pagarPeaje()
}

Class Auto extends Vehiculo {
    tarifa()
}

Class Camion extends Vehiculo {
    cantidadDeEjes

    tarifa()
}

Class ConTelePeaje {
    peajesDisponibles

    pagarSegunMetodo(unMonto)
}

Class ConSube {
    saldoSube

    pagarSegunMetodo(unMonto)
}

Class ConEfectivo {
    saldoEnEfectivo

    pagarSegunMetodo(unMonto)
}

interface metodoDePago {
    pagarSegunMetodo(unMonto)
}

Autopista --> "*" Vehiculo : vehiculos
Vehiculo -l-> metodoDePago
ConTelePeaje .u.|> metodoDePago
ConSube .u.|> metodoDePago
ConEfectivo .u.|> metodoDePago



@enduml