@startuml diagrama

Class Persona {
    edad
    consolas

    puedeJugar(unJuego)
}

interface juego {
    puedeJugarSegunCondiciones(unaPersona)
}

object pelota {
    puedeJugarSegunCondiciones(unaPersona)
}

Class JuegoDeMesa {
    edadMinima 
    edadMaxima 

    puedeJugarSegunCondiciones(unaPersona)
}

Class VideoJuegos {
    genero
    consolaPosible

    puedeJugarSegunCondiciones(unaPersona)
    tieneConsolaPosible(unasConsolas) 
}

interface genero {
    estaEnElRangoDeEdad(unaEdad)
}

Class Genero {
    var edadMinima

    estaEnElRangoDeEdad(unaEdad)
}

Persona ..> juego : juego
pelota .u.|> juego
JuegoDeMesa .u.|> juego
VideoJuegos .u.|> juego
VideoJuegos --> genero
Genero .u.|> genero

@enduml